### PR TITLE
update Nonce size limits

### PR DESCRIPTION
**Pull request by chendave**
This change wants to sync with https://github.com/veraison/ear/pull/35.

### CODE REVIEW

**Comment by chendave** [comment]
cc @setrofim

**Comment by chendave** [comment]
@yogeshbdeshpande, I guess @setrofim is on vacation? Do you have privilege to merge this?

**Review by thomas-fossati — APPROVED** [review]

**Review by yogeshbdeshpande — APPROVED** [review]
LGTM!

**Comment by yogeshbdeshpande** [comment]
@chendave Thank you for making the change!

**Comment by thomas-fossati** [comment]
Hi, @chendave, thanks!

Hint: next time you need a review, please select your reviewers using the "Reviewers" tab.  This went completely unnoticed.

**Comment by chendave** [comment]
> Hint: next time you need a review, please select your reviewers using the "Reviewers" tab. 

I don't have the privilege to do that. 😄

**Comment by thomas-fossati** [comment]
> Let me do the necessary admin

already done

**Comment by chendave** [comment]
> already done

cool, works for me now!

**Pull request merged**
